import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),ts=require('../broadcast/vendor/typescript/typescript.cjs'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'cp3-contracts-'));
for(const name of ['model','providers','palette','contours','futurecast']){const source=fs.readFileSync(new URL(`../../src/synoptic/${name}.ts`,import.meta.url),'utf8');fs.writeFileSync(path.join(dir,name+'.js'),ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText);}
const {parseSurface,timestamp,vectorPayload,gridBytes}=require(path.join(dir,'providers.js')),{PRODUCTS}=require(path.join(dir,'model.js')),{colorFor,legendFor}=require(path.join(dir,'palette.js'));
process.on('exit',()=>fs.rmSync(dir,{recursive:true,force:true}));
test('WPC month/day/hour and wrapped front positions preserve coordinates',()=>{const now=Date.UTC(2026,8,28,5);const p=parseSurface('VALID 092803Z\nHIGHS 1022 7384\nCOLD 4063 3963\n 3763 36100',now);assert.equal(p.time,Date.UTC(2026,8,28,3));assert.deepEqual(p.objects[0].points,[[-84,73]]);assert.deepEqual(p.objects[1].points,[[-63,40],[-63,39],[-63,37],[-100,36]]);assert.throws(()=>parseSurface('VALID 092703Z\nCOLD 4063 3963',now),/validity/);});
test('advisory and outlook timestamps use source time rather than retrieval time',()=>{assert.equal(timestamp('202609280100'),Date.UTC(2026,8,28,1));assert.equal(timestamp('300 AM GMT Mon Sep 28 2026'),Date.UTC(2026,8,28,3));assert.equal(timestamp('not supplied'),null);});
test('MRMS categorical flags remain discrete including tropical codes',()=>{const p=PRODUCTS.find(x=>x.id==='mrms-type');assert.deepEqual(colorFor(p,91),[237,146,80]);assert.equal(colorFor(p,2),null);assert.equal(colorFor(p,-3),null);assert.equal(legendFor(p).length,7);assert.notDeepEqual(colorFor(p,3),colorFor(p,6));});
test('negative azimuthal shear is retained and distinct from positive shear',()=>{const p=PRODUCTS.find(x=>x.id==='mrms-shear');assert.ok(colorFor(p,-.01));assert.notDeepEqual(colorFor(p,-.01),colorFor(p,.01));});
test('analysis byte-range failure refuses whole multi-field download',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>++calls===1?new Response('1:0:d:TMP:2 m above ground:x\n2:128:d:DPT:2 m above ground:x'):new Response(new Uint8Array(200));try{await assert.rejects(gridBytes(PRODUCTS.find(p=>p.id==='rtma-temperature'),{key:'https://fixture.test/data',time:Date.now()},new AbortController().signal),/bounded GRIB/);}finally{globalThis.fetch=original;}});
test('severe watch scene excludes expired and unrelated watches',async()=>{const original=globalThis.fetch;const future=new Date(Date.now()+3600000).toISOString(),past=new Date(Date.now()-1).toISOString();globalThis.fetch=async url=>{assert.ok(!String(url).includes('limit='),'active endpoint rejects limit');return Response.json({features:[['Tornado Watch',future],['Severe Thunderstorm Watch',future],['Flood Watch',future],['Tornado Watch',past]].map(([event,expires])=>({type:'Feature',geometry:{type:'Polygon',coordinates:[[[-99,30],[-98,30],[-98,31],[-99,30]]]},properties:{event,expires,status:'Actual',messageType:'Alert'}}))});};try{const p=await vectorPayload(PRODUCTS.find(p=>p.id==='watches'),new AbortController().signal);assert.equal(p.data.features.length,2);assert.equal(p.time,null);assert.equal(p.timeLabel,'ALERT TIMES VARY');}finally{globalThis.fetch=original;}});

test('analysis labels and contours retain the sampled Mercator domain',()=>{const {analyzedObjects}=require(path.join(dir,'contours.js'));const n=120,values=new Float32Array(n*n);for(let y=0;y<n;y++)for(let x=0;x<n;x++)values[y*n+x]=x;const data=analyzedObjects(values,n,n,[-100,20,-90,40],[60]);assert.ok(data.features.some(f=>f.geometry.type==='Point'));const line=data.features.find(f=>f.geometry.type==='MultiLineString');assert.ok(line.geometry.coordinates.length);for(const segment of line.geometry.coordinates)for(const [lon,lat] of segment){assert.ok(lon>-96&&lon<-94);assert.ok(lat>=20&&lat<=40);}});

test('NHC advisory time zones are explicit and storm names normalize across point/cone layers',async()=>{
 assert.equal(timestamp('500 AM AST Tue Sep 29 2026'),Date.UTC(2026,8,29,9));assert.equal(timestamp('1100 PM EDT Mon Sep 28 2026'),Date.UTC(2026,8,29,3));
 const original=globalThis.fetch,now=new Date().toISOString(),geometry={type:'Polygon',coordinates:[[[-60,20],[-58,20],[-58,23],[-60,20]]]};
 globalThis.fetch=async url=>{const u=String(url);if(u.includes('/query?'))return Response.json({type:'FeatureCollection',features:[{type:'Feature',geometry,properties:{STORMNAME:u.includes('/1/')?'Tropical Storm Test':'Test',ADVDATE:now,ADVISNUM:'7'}}]});if(/\/\d+\?/.test(u))return Response.json({drawingInfo:{renderer:{symbol:{color:[255,255,255,255]}}}});return Response.json({layers:[{id:1,name:'AT1 Forecast Points',type:'Feature Layer'},{id:2,name:'AT1 Forecast Cone',type:'Feature Layer'}]});};
 try{const p=await vectorPayload(PRODUCTS.find(p=>p.id==='tropical-cone'),new AbortController().signal);assert.deepEqual(p.data.features.map(f=>f.properties._storm),['Test','Test']);assert.deepEqual(p.data.features[1].geometry,geometry,'official cone geometry altered');assert.equal(p.time,Date.parse(now));}finally{globalThis.fetch=original;}
});
test('surge overlay requests active storm-surge alerts and excludes unrelated hazards',async()=>{const original=globalThis.fetch;globalThis.fetch=async url=>{assert.match(String(url),/Storm%20Surge/);assert.ok(!String(url).includes('limit='));return Response.json({features:['Storm Surge Warning','Storm Surge Watch','Tornado Watch'].map(event=>({type:'Feature',geometry:{type:'Polygon',coordinates:[[[-99,30],[-98,30],[-98,31],[-99,30]]]},properties:{status:'Actual',messageType:'Alert',event,expires:new Date(Date.now()+60000).toISOString()}}))});};try{const p=await vectorPayload(PRODUCTS.find(p=>p.id==='surge'),new AbortController().signal);assert.equal(p.data.features.length,2);assert.equal(p.data.features[0].properties._color,'#b524f7');}finally{globalThis.fetch=original;}});

test('hourly 24-hour QPE allows its publication cadence without relaxing live radar freshness',()=>{assert.equal(PRODUCTS.find(p=>p.id==='mrms-qpe24').ageMinutes,90);assert.equal(PRODUCTS.find(p=>p.id==='mrms-reflectivity').ageMinutes,30);});
