import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),ts=require('../broadcast/vendor/typescript/typescript.cjs'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'cp3-radar-'));
const src=fs.readFileSync(new URL('../../src/current-weather/public-imagery.ts',import.meta.url),'utf8');fs.writeFileSync(path.join(dir,'radar.cjs'),ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText);const {RadarImagery,currentRadarTime,PublicImagery}=require(path.join(dir,'radar.cjs'));process.on('exit',()=>fs.rmSync(dir,{recursive:true,force:true}));
function manager(){const removed=[],layers=new Set(['old']);const map={getLayer:id=>layers.has(id),removeLayer:id=>{removed.push(id);layers.delete(id)},getSource:()=>false};return {m:new RadarImagery(map,{product:'radar',anchor:'a',opacity:1,onError(){}}),removed};}
test('current radar boundary rejects stale, nonfinite and future timestamps',()=>{const now=Date.now();assert.equal(currentRadarTime(now-900000,now),true);assert.equal(currentRadarTime(now-900001,now),false);assert.equal(currentRadarTime(now+60001,now),false);assert.equal(currentRadarTime(NaN,now),false);});
test('corrupt newest frame falls back to an older current frame',async()=>{const {m}=manager(),now=Date.now(),attempts=[];m.runtimes.set('KEWX',{times:[now-600000,now-300000,now],selected:null,activeLayer:null,serial:0});m.loadSite=async(id,t)=>{attempts.push(t);if(t===now)throw Error('Corrupt PNG');m.runtimes.get(id).selected=t;};await m.loadNewestUsable('KEWX');assert.deepEqual(attempts,[now,now-300000]);assert.equal(m.currentLoadedTimeKey,now-300000);});
test('stale imagery is removed even without another fetch',()=>{const {m,removed}=manager();m.runtimes.set('KEWX',{times:[],selected:Date.now()-900001,activeLayer:'old',serial:0});m.expireSites();assert.deepEqual(removed,['old']);assert.equal(m.currentLoadedTimeKey,null);assert.match(m.statusDetail,/stale frame removed/);});
test('no fresh candidate never attempts a stale renderable frame',async()=>{const {m}=manager();m.runtimes.set('KEWX',{times:[Date.now()-3600000],selected:null,activeLayer:null,serial:0});m.loadSite=()=>assert.fail('stale load attempted');await assert.rejects(m.loadNewestUsable('KEWX'),/15-minute/);});
test('MRMS fallback has its own timestamp and never uses a site label',()=>{const {m}=manager();m.mosaic={currentLoadedTimeKey:Date.now()-60000};m.emit();assert.match(m.sourceLabel,/MRMS MOSAIC/);assert.equal(m.currentLoadedTimeKey,m.mosaic.currentLoadedTimeKey);});
test('a failed replacement leaves displayed site timestamp unchanged',async()=>{const {m}=manager(),time=Date.now()-1000;m.runtimes.set('KEWX',{times:[time],selected:null,activeLayer:null,serial:0});m.map.getBounds=()=>({getWest:()=>-100,getEast:()=>-97,getSouth:()=>28,getNorth:()=>31});m.map.getCanvas=()=>({width:300,height:200});m.radarResponse=async()=>new Response('<error/>',{headers:{'content-type':'text/xml'}});await assert.rejects(m.loadSite('KEWX',time));assert.equal(m.runtimes.get('KEWX').selected,null);});
