import {useRadarOverlay} from './RadarOverlay';
import {useForecastGraphics} from './ForecastGraphicsHost';
import{ToolIcon,IconButton}from'./OnAirIcons';
import{useBroadcast}from'../broadcast';
import{useQpf}from'./QpfHost';
import{useCurrentWeather}from'../current-weather/CurrentWeather';
import{useEwxAlerts}from'../current-weather/EwxAlerts';
import{useGraphics}from'../broadcast-graphics/Graphics';
import{useSynoptic}from'../synoptic/Scene';
import{OVERLAYS,useOnAirTools}from'../synoptic/OnAirTools';
import{PRODUCTS}from'../synoptic/model';
import type{Options}from'../current-weather/model';
import'./onAirMenu.css';
export function useOnAirCommands(){const qpf=useQpf(),radar=useRadarOverlay(),forecast=useForecastGraphics(),weather=useCurrentWeather(),synoptic=useSynoptic(),tools=useOnAirTools(),graphics=useGraphics(),ewx=useEwxAlerts();return(command:string):boolean=>{
 if(command==='bar-add'){if(forecast.active){forecast.showTitle();}else if(synoptic.active)synoptic.edit({titleVisible:true});else if(!graphics.visible.title)graphics.toggle('title');return true;}
 if(command==='bar-refresh'){if(forecast.active){forecast.showTitle(true);}else if(synoptic.active){const{title,time,...rest}=synoptic.snapshot.settings.textOverrides??{};synoptic.edit({titleVisible:true,title:'',textOverrides:rest});}else{graphics.edit({manual:false});if(!graphics.visible.title)graphics.toggle('title');}return true;}
 if(command==='ewx-toggle'){ewx.edit({enabled:!ewx.state.enabled});return true;}
 if(command==='ewx-refresh'){ewx.refresh();return true;}
 if(command==='radar-toggle'){radar.toggle();return true;}
 if(command==='radar-off'){radar.setEnabled(false);return true;}
 if(command==='sweeps'){radar.edit({sweepsEnabled:!radar.options.sweepsEnabled});return true;}
 if(command==='pen'){tools.setMode(tools.mode==='pen'?'none':'pen');return true;}
 if(command==='track'){tools.setMode(tools.mode==='track'?'none':'track');return true;}
 if(command==='pen-undo'){tools.edit({strokes:tools.snapshot.objects.strokes.slice(0,-1)});return true;}
 if(command==='pen-clear'){tools.edit({strokes:[]});return true;}
 if(command==='track-clear'){tools.edit({track:[]});return true;}
 if(command.startsWith('speed:')){const mph=Number(command.slice(6));if(Number.isFinite(mph)&&mph>=1&&mph<=150)tools.edit({mph});return true;}
 if(command.startsWith('color:')){const color=command.slice(6);if(/^#[a-f0-9]{6}$/i.test(color))tools.setColor(color);return true;}
 if(command.startsWith('overlay:')){const id=command.slice(8);if(OVERLAYS.some(p=>p.id===id))tools.toggle(id);return true;}
 if(command.startsWith('radar:')){const field=command.slice(6);if(['reflectivity','velocity','hydro'].includes(field)){radar.setEnabled(true);radar.edit({radarField:field as Options['radarField'],mrmsEnabled:false});}return true;}
 if(command.startsWith('satellite:')){const feed=command.slice(10);if(['longwave','shortwave','visible','water_vapor','snow_ice'].includes(feed)){synoptic.setProduct(null);weather.setProduct('satellite');weather.edit({satelliteFeed:feed as Options['satelliteFeed']});}return true;}
 if(command.startsWith('mrms:')){const id=command.slice(5);if(PRODUCTS.some(p=>p.id===id&&p.family==='mrms')){weather.setProduct('map');synoptic.setProduct(id);}return true;}
 if(command==='layers-off'){radar.setEnabled(false);if(qpf.active)qpf.setEnabled(false);for(const id of Object.keys(tools.enabled))if(tools.enabled[id])tools.toggle(id);weather.setProduct('map');synoptic.setProduct(null);return true;}
 if(command==='overlays-refresh'){tools.refresh();return true;}
 return false;
};}
export function BroadcastToolButtons({command,ewx=false,enabled={},draw=true,radar=false,sweeps=false}:{command:(value:string)=>void;ewx?:boolean;enabled?:Record<string,boolean>;draw?:boolean;radar?:boolean;sweeps?:boolean}){
 const summary=(icon:string,label:string)=><><ToolIcon name={icon}/><span>{label}</span></>;
 const exclusive=(e:React.SyntheticEvent<HTMLDetailsElement>)=>{if(e.currentTarget.open)e.currentTarget.parentElement?.querySelectorAll(':scope > details').forEach(node=>{if(node!==e.currentTarget)(node as HTMLDetailsElement).open=false;});};
 return <div className="onair-toolbar" aria-label="Broadcast tools">
 <IconButton icon="add" label="Add / show title bar" short="Title" onClick={()=>command('bar-add')}/><IconButton icon="refresh" label="Refresh title from scene" short="Title" onClick={()=>command('bar-refresh')}/>
 <IconButton icon="alerts" label={`EWX alert scroll ${ewx?'on':'off'}`} short="EWX" aria-pressed={ewx} onClick={()=>command('ewx-toggle')}/>
 {OVERLAYS.map(item=><IconButton key={item.id} icon={item.id==='warnings'?'warning':item.id==='cone'?'cone':item.id==='surge'?'surge':'lightning'} label={item.label} short={item.id==='warnings'?'Warn':item.id==='cone'?'Cone':item.id==='surge'?'Surge':'GLM'} aria-pressed={enabled[item.id]??false} onClick={()=>command(`overlay:${item.id}`)}/>)}
 <IconButton icon="radar" label="Toggle radar overlay" short="Radar" aria-pressed={radar} onClick={()=>command('radar-toggle')}/><IconButton icon="sweep" label="Toggle radar sweeps" short="Sweep" aria-pressed={sweeps} onClick={()=>command('sweeps')}/><IconButton icon="refresh" label="Refresh overlays" short="Layers" onClick={()=>command('overlays-refresh')}/>
 <details onToggle={exclusive}><summary title="Radar products" aria-label="Radar products">{summary('radar','Radar')}</summary><div className="onair-submenu">
 <button title="Turn radar off" onClick={()=>command('radar-off')}>OFF</button><button title="Site reflectivity" onClick={()=>command('radar:reflectivity')}>REF</button><button title="Radial velocity" onClick={()=>command('radar:velocity')}>VEL</button><button title="Hydrometeor classification" onClick={()=>command('radar:hydro')}>HCA</button>
 <label>MRMS<select aria-label="MRMS product" defaultValue="" onChange={e=>{if(e.target.value)command(`mrms:${e.target.value}`);e.target.value='';}}><option value="">Choose layer…</option>{PRODUCTS.filter(p=>p.family==='mrms').map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>
 </div></details>
 <details onToggle={exclusive}><summary title="Satellite feeds" aria-label="Satellite feeds">{summary('satellite','Sat')}</summary><div className="onair-submenu">{[['longwave','IR','Longwave infrared'],['visible','VIS','Visible'],['water_vapor','WV','Water vapor'],['shortwave','SWIR','Shortwave infrared'],['snow_ice','Snow','Snow / ice']].map(([id,label,full])=><button key={id} title={full} aria-label={full} onClick={()=>command(`satellite:${id}`)}>{label}</button>)}</div></details>
 <details onToggle={exclusive}><summary title="Drawing tools" aria-label="Drawing tools">{summary('pen','Draw')}</summary><div className="onair-submenu"><IconButton icon="pen" label="Pen on / off" short="Pen" disabled={!draw} onClick={()=>command('pen')}/><IconButton icon="undo" label="Undo stroke" short="Undo" onClick={()=>command('pen-undo')}/><IconButton icon="clear" label="Clear ink" short="Clear" onClick={()=>command('pen-clear')}/><label>Color<input aria-label="Pen color" type="color" defaultValue="#fff000" onChange={e=>command(`color:${e.target.value}`)}/></label>{!draw&&<small>Draw on the operator canvas.</small>}</div></details>
 <details onToggle={exclusive}><summary title="Storm direction and city timing" aria-label="Storm tracking tools">{summary('track','Track')}</summary><div className="onair-submenu"><IconButton icon="track" label="Place direction: click origin, then ahead" short="Place" disabled={!draw} onClick={()=>command('track')}/><IconButton icon="clear" label="Clear track" short="Clear" onClick={()=>command('track-clear')}/><label>mph<input aria-label="Storm speed (mph)" type="number" min="1" max="150" defaultValue="30" onChange={e=>command(`speed:${e.target.value}`)}/></label><small>Operator estimate · visible cities near path.</small></div></details>
 <IconButton icon="off" label="Weather layer off" short="Off" onClick={()=>command('layers-off')}/><IconButton icon="refresh" label="Refresh EWX alerts" short="EWX" onClick={()=>command('ewx-refresh')}/>
 </div>;
}
export function HiddenPlayback(){const forecast=useForecastGraphics(),base=useCurrentWeather(),radar=useRadarOverlay(),w=radar.enabled?{...radar,product:'radar' as const}:base,s=useSynoptic(),q=useQpf(),b=useBroadcast();const imagery=w.product==='radar'||w.product==='satellite',weather=s.active||imagery,playing=s.active&&!radar.enabled?s.playing:imagery?w.snapshot.playing:b.state.transport==='playing';const disabled=s.active&&!radar.enabled?s.snapshot.frames.length<2:imagery?w.snapshot.times.length<2:!playing&&!b.canPlay;
 const step=(n:-1|1)=>s.active&&!radar.enabled?s.step(n):imagery?w.controller.step(n):n<0?b.previous():b.next();const loop=s.active&&!radar.enabled?s.snapshot.settings.loop:imagery?w.options.loop:b.state.loop;
 return <div className="onair-playback" aria-label="Hidden menu playback"><IconButton icon="previous" label={weather?'Previous weather frame':'Previous scene'} onClick={()=>step(-1)}/><IconButton icon={playing?'pause':'play'} label={playing?'Pause playback':'Play playback'} disabled={disabled} onClick={()=>s.active&&!radar.enabled?s.play():imagery?w.controller.play():playing?b.pause():b.play()}/><IconButton icon="next" label={weather?'Next weather frame':'Next scene'} onClick={()=>step(1)}/><IconButton icon="loop" label="Toggle playback loop" aria-pressed={loop} onClick={()=>s.active&&!radar.enabled?s.edit({loop:!loop}):imagery?w.edit({loop:!loop}):b.setLoop(!loop)}/><IconButton icon="refresh" label="Refresh weather" onClick={()=>void(radar.enabled?radar.controller.refresh():s.active?s.controller.refresh():q.active?q.controller.refresh():forecast.active?forecast.refreshData():w.controller.refresh())}/>{imagery&&(!s.active||radar.enabled)&&<><IconButton icon="latest" label="Latest weather frame" disabled={!w.snapshot.times.length} onClick={()=>{w.controller.stop();void w.controller.seek(w.snapshot.times[w.snapshot.times.length-1]);}}/><input aria-label="Weather frame" type="range" min="0" max={Math.max(0,w.snapshot.times.length-1)} disabled={disabled} value={Math.max(0,w.snapshot.times.indexOf(w.snapshot.selectedTime??0))} onChange={e=>{w.controller.stop();void w.controller.seek(w.snapshot.times[Number(e.target.value)]);}}/></>}</div>;
}
export function OnAirMenu({onDrawStart}:{onDrawStart?:()=>void}){const qpf=useQpf(),forecast=useForecastGraphics(),radar=useRadarOverlay(),dispatch=useOnAirCommands(),command=(value:string)=>{dispatch(value);if(value==='pen'||value==='track')onDrawStart?.();},ewx=useEwxAlerts(),tools=useOnAirTools(),weather=useCurrentWeather(),synoptic=useSynoptic();const bounds=synoptic.map?.getBounds();const flashes=tools.snapshot.overlays[1]?.payload?.data?.features.filter(f=>f.geometry.type==='Point'&&(!bounds||bounds.contains(f.geometry.coordinates.slice(0,2)as[number,number]))).length;
 return <><BroadcastToolButtons command={command} ewx={ewx.state.enabled} enabled={tools.enabled} radar={radar.enabled} sweeps={radar.options.sweepsEnabled}/><details className="onair-status"><summary title="Weather status and radar site" aria-label="Weather status and radar site"><ToolIcon name="info"/><span>Status / site</span></summary><div className="onair-status-body"><span>{synoptic.active?`${PRODUCTS.find(p=>p.id===synoptic.snapshot.productId)?.title} · ${synoptic.snapshot.status}`:qpf.active?qpf.snapshot.message:forecast.active?forecast.message:weather.snapshot.message}</span>{radar.enabled&&<><span>{radar.snapshot.message}</span><label>Radar site<select value={radar.snapshot.primaryRadarId??''} onChange={e=>void radar.controller.setPrimaryRadar(e.target.value)}><option value="">Select radar</option>{radar.snapshot.radarSites.map(site=><option key={site.id} value={site.id}>{site.city} — {site.id}</option>)}</select></label></>}{OVERLAYS.map((p,i)=>tools.enabled[p.id]&&<span key={p.id}>{p.label}: {tools.snapshot.overlays[i]?.status}{p.id==='lightning'&&flashes!==undefined?` · ${flashes} flashes in view`:''}</span>)}{tools.mode!=='none'&&<strong>{tools.mode==='pen'?'PEN ACTIVE · drag on map':'TRACK ACTIVE · click origin, then direction'} <button onClick={()=>tools.setMode('none')}>Done</button></strong>}</div></details></>;
}
