import type { BarStyles } from '../broadcast-graphics/barStyles';
import type { FeatureCollection } from 'geojson';
export type Family = 'surface' | 'severe' | 'tropical' | 'lightning' | 'analysis' | 'mrms';
export interface Product { id: string; title: string; family: Family; source: string; kind: 'grid' | 'glm' | 'arcgis' | 'alerts' | 'surface' | 'manual'; field?: string; service?: string; match?: string; ageMinutes: number; units?: string; range?: [number, number]; }
const arc = (id: string, title: string, family: Family, service: string, match: string, ageMinutes = 1440): Product => ({ id, title, family, kind: 'arcgis', source: family === 'tropical' ? 'NOAA / NHC' : 'NOAA / SPC', service, match, ageMinutes });
const spc = 'https://mapservices.weather.noaa.gov/vector/rest/services/outlooks/SPC_wx_outlks/MapServer';
const nhc = 'https://mapservices.weather.noaa.gov/tropical/rest/services/tropical/NHC_tropical_weather/MapServer';
export const PRODUCTS: Product[] = [
 {id:'surface-national',title:'National Surface Analysis',family:'surface',kind:'surface',source:'NOAA / WPC',ageMinutes:360},
 {id:'surface-regional',title:'Regional Surface Analysis',family:'surface',kind:'surface',source:'NOAA / WPC',ageMinutes:360},
 {id:'surface-radar',title:'Fronts + Precipitation',family:'surface',kind:'surface',source:'NOAA / WPC',ageMinutes:360},
 {id:'surface-satellite',title:'Fronts + Cloud Cover',family:'surface',kind:'surface',source:'NOAA / WPC',ageMinutes:360},
 {id:'future-fronts',title:'Futurecast Surface Setup',family:'surface',kind:'manual',source:'Operator forecast objects',ageMinutes:0},
 {id:'airmass',title:'Air Mass / Moisture / Cold / Warm',family:'surface',kind:'manual',source:'Operator analysis',ageMinutes:0},
 {id:'alerts',title:'Active Alerts',family:'severe',kind:'alerts',source:'NWS Alerts API',ageMinutes:5},
 {id:'warnings',title:'Local Warnings',family:'severe',kind:'alerts',source:'NWS Alerts API',field:'Warning',ageMinutes:5},
 ...[['spc-day1','SPC Day 1 Categorical','^Day 1 Categorical Outlook$'],['spc-tornado','SPC Day 1 Tornado Probability','^Day 1 Probabilistic Tornado Outlook$'],['spc-hail','SPC Day 1 Hail Probability','^Day 1 Probabilistic Hail Outlook$'],['spc-wind','SPC Day 1 Wind Probability','^Day 1 Probabilistic Wind Outlook$'],['spc-day2','SPC Day 2 Categorical','^Day 2 Categorical Outlook$'],['spc-day3','SPC Day 3 Categorical','^Day 3 Categorical Outlook$'],...Array.from({length:5},(_,i)=>[`spc-day${i+4}`,`SPC Day ${i+4} Probability`,`^Day ${i+4} Probabilistic Outlook$`])].map(([id,title,match])=>arc(id,title,'severe',spc,match)),
 {id:'watches',title:'Severe Weather Watches',family:'severe',kind:'alerts',field:'Watch',source:'NWS Alerts · watch areas',ageMinutes:5},
 arc('mesoscale','Mesoscale Discussions','severe','https://mapservices.weather.noaa.gov/vector/rest/services/outlooks/spc_mesoscale_discussion/MapServer','',360),
 ...[['tropical-atlantic','Atlantic Basin','Forecast (Points|Track|Cone)$'],['tropical-gulf','Gulf / Caribbean','Forecast (Points|Track|Cone)$'],['tropical-pacific','Eastern Pacific','Forecast (Points|Track|Cone)$'],['tropical-track','Regional Storm Track','Forecast (Points|Track)$'],['tropical-cone','Cone + Forecast Points','Forecast (Points|Track|Cone)$'],['tropical-warnings','Cone + Watches / Warnings','(Forecast Cone|Watch-Warning)$'],['tropical-winds','Track + Wind Radii','(Forecast Track|Forecast Wind Radii|Advisory Wind Field)$'],['tropical-outlook','Tropical Outlook','Seven-Day:'],['tropical-impacts','Local Tropical Impacts','(Watch-Warning|Advisory Wind Field)$'],['tropical-summary','Storm Summary','Forecast Points$']].map(([id,title,match])=>arc(id,title,'tropical',nhc,match,720)),
 ...['rtma','urma'].flatMap(type=>[['temperature','Temperature','TMP','°F',-20,120],['dewpoint','Dewpoint','DPT','°F',-20,85],['wind','Wind Speed','WIND','mph',0,80],['pressure','Surface Pressure','PRES','hPa',850,1050]].map(([id,title,field,units,min,max])=>({id:`${type}-${id}`,title:`${type.toUpperCase()} ${title} Analysis`,family:'analysis',kind:'grid',source:`NOAA / ${type.toUpperCase()}`,field,ageMinutes:type==='rtma'?180:2400,units,range:[min,max]} as Product))),
 ...[['mrms-reflectivity','Reflectivity Mosaic','SeamlessHSR_00.00','dBZ',0,80],['mrms-composite','Composite Reflectivity','MergedReflectivityQCComposite_00.50','dBZ',0,80],['mrms-qpe1','1-Hour Rainfall','RadarOnly_QPE_01H_00.00','in',0,5],['mrms-qpe24','24-Hour Rainfall','RadarOnly_QPE_24H_00.00','in',0,15],['mrms-rate','Rainfall Rate','PrecipRate_00.00','in/hr',0,5],['mrms-type','Precipitation Type','PrecipFlag_00.00','category',0,7],['mrms-tops','Echo Tops · 18 dBZ','EchoTop_18_00.50','kft',0,60],['mrms-hail','MESH / Hail Estimate','MESH_00.50','in',0,4],['mrms-shear','Low-Level Azimuthal Shear','MergedAzShear_0-2kmAGL_00.50','s⁻¹',-.02,.02],['mrms-flood','Rainfall / Flash-Flood Guidance','FLASH_QPE_FFG01H_00.00','ratio',0,3]].map(([id,title,field,units,min,max])=>({id,title:`MRMS ${title}`,family:'mrms',kind:'grid',source:'NOAA / MRMS',field,ageMinutes:30,units,range:[min,max]} as Product)),
 ...[['glm-flashes','Lightning Flashes'],['glm-density','Lightning Flash Density'],['glm-trend','Lightning Recent Activity'],['glm-radar','Lightning + Radar'],['glm-satellite','Lightning + Satellite']].map(([id,title])=>({id,title,family:'lightning',kind:'glm',source:'NOAA GOES-19 GLM · total lightning',ageMinutes:10} as Product)),
];
export interface WeatherObject { id: string; kind: 'cold'|'warm'|'stationary'|'occluded'|'trough'|'dryline'|'H'|'L'|'text'|'arrow'|'hurricane'|'tropical-storm'; points: [number,number][]; text: string; origin: 'operator'|'WPC'; }
export interface Frame { time: number; key: string; }
export interface SceneSettings { barStyles?: BarStyles; titleLayout?: {x:number;y:number;width:number}; textOverrides?: Record<string,string>; title: string; subtitle: string; lower: string; opacity: number; titleVisible: boolean; legendVisible: boolean; labels: boolean; detailsVisible: boolean; objects: WeatherObject[]; windowMinutes: number; loop: boolean; background: 'none'|'radar'|'satellite'; forecastTime: string; storm: string; manualSurface: boolean; contours: boolean; }
export const defaults = (): SceneSettings => ({title:'',subtitle:'',lower:'',opacity:.72,titleVisible:true,legendVisible:true,labels:true,detailsVisible:false,objects:[],windowMinutes:5,loop:true,background:'none',forecastTime:'',storm:'',manualSurface:false,contours:false});
export interface Payload { timeLabel?: string; time: number|null; expires: number|null; data?: FeatureCollection; objects?: WeatherObject[]; image?: string; coordinates?: [number,number][]; legend?: {label:string;color:string}[]; note?: string; }
export interface PackSnapshot { productId: string|null; settings: SceneSettings; payload: Payload|null; backgroundPayload?: Payload|null; status: string; frames: Frame[]; index: number; }
export const emptyPack = ():PackSnapshot => ({productId:null,settings:defaults(),payload:null,status:'OFF',frames:[],index:0});
export const productFor = (key?:string) => PRODUCTS.find(p=>`synoptic.${p.id}`===key) ?? null;
