import {BarLibrary} from '../broadcast-graphics/BarLibrary';
import {barAttributes,barPresentation} from '../broadcast-graphics/barStyles';
import {createContext,useContext,useEffect,useLayoutEffect,useMemo,useState,type ReactNode} from 'react';
import type {Map as WeatherMap} from 'maplibre-gl';
import {useBroadcast} from '../broadcast';
import {defaults,emptyPack,PRODUCTS,productFor,type PackSnapshot,type SceneSettings,type WeatherObject} from './model';
import {SynopticRuntime} from './runtime';
import {TitleBar,EditableText,titleLayout} from './Chrome';
import './synoptic.css';
interface Runtime {active:boolean;snapshot:PackSnapshot;controller:SynopticRuntime;map:WeatherMap|null;connect:(m:WeatherMap)=>()=>void;edit:(patch:Partial<SceneSettings>)=>void;playing:boolean;play:()=>void;step:(d:number)=>void;selected:string|null;select:(id:string|null)=>void;drawing:WeatherObject['kind']|null;draw:(kind:WeatherObject['kind']|null)=>void;}
const Context=createContext<Runtime|null>(null);
export const useSynoptic=()=>{const c=useContext(Context);if(!c)throw Error('Synoptic provider missing');return c;};
export function SynopticHost({children}:{children:ReactNode}){
 const {programScene,state}=useBroadcast(),product=productFor(programScene?.contentKey),scene=state.programItemId??programScene?.id??'startup';
 const [snapshot,setSnapshot]=useState(emptyPack),[map,setMap]=useState<WeatherMap|null>(null),[playing,setPlaying]=useState(false),[selected,select]=useState<string|null>(null),[drawing,draw]=useState<WeatherObject['kind']|null>(null);
 const [settings,setSettings]=useState<Record<string,SceneSettings>>(()=>{try{return JSON.parse(localStorage.getItem('rbrwx-synoptic-scenes-v1')??'{}');}catch{return {};}});
 const controller=useMemo(()=>new SynopticRuntime(setSnapshot),[]),current={...defaults(),...settings[scene],background:settings[scene]?.background??(product?.id.endsWith('-radar')?'radar':product?.id.endsWith('-satellite')?'satellite':'none')} as SceneSettings;
 const edit=(patch:Partial<SceneSettings>)=>setSettings(old=>({...old,[scene]:{...current,...old[scene],...patch}}));
 useLayoutEffect(()=>{controller.select(product,current);},[controller,product,settings,scene]);
 useEffect(()=>{if(!map||!product)return;const id=product.id;
  const view=id==='tropical-pacific'?{center:[-120,22] as [number,number],zoom:3.5}:id==='tropical-gulf'?{center:[-85,23] as [number,number],zoom:4.5}:product.family==='tropical'?{center:[-55,28] as [number,number],zoom:3}:id!=='surface-regional'&&id!=='warnings'?{center:[-98,38] as [number,number],zoom:3.6}:null;
  if(view)map.easeTo({...view,duration:0});
 },[map,scene,product]);
 useEffect(()=>{setPlaying(false);select(null);draw(null);},[scene]);
 useEffect(()=>{try{localStorage.setItem('rbrwx-synoptic-scenes-v1',JSON.stringify(settings));}catch{/* Persistence failure leaves the current scene editable. */}},[settings]);
 useEffect(()=>()=>controller.disconnect(),[controller]);
 useEffect(()=>{if(!product)return;const timer=setInterval(()=>void controller.refresh(),product.family==='lightning'?60000:120000);return()=>clearInterval(timer);},[product,controller]);
 const step=(d:number)=>{setPlaying(false);const n=snapshot.frames.length;if(!n)return;const i=snapshot.index+d;if(i>=0&&i<n)void controller.loadFrame(i);else if(current.loop)void controller.loadFrame((i+n)%n);};
 useEffect(()=>{if(!playing)return;let busy=false;const timer=setInterval(()=>{if(busy)return;const s=controller.snapshot,n=s.frames.length;let i=s.index+1;if(i>=n){if(!s.settings.loop){setPlaying(false);return;}i=0;}busy=true;void controller.loadFrame(i).finally(()=>{busy=false;});},900);return()=>clearInterval(timer);},[playing,controller]);
 return <Context.Provider value={{active:!!product,snapshot,controller,map,connect:m=>{setMap(m);const release=controller.connect(m);return()=>{release();setMap(null);};},edit,playing,play:()=>setPlaying(p=>!p),step,selected,select,drawing,draw}}>{children}</Context.Provider>;
}
export function SynopticPlayback(){const c=useSynoptic();if(!c.active)return null;return <div className="synoptic-playback"><button onClick={()=>c.step(-1)} aria-label="Previous weather frame">|◀</button><button disabled={c.snapshot.frames.length<2} onClick={c.play}>{c.playing?'Ⅱ':'▶'}</button><button onClick={()=>c.step(1)} aria-label="Next weather frame">▶|</button><button aria-pressed={c.snapshot.settings.loop} onClick={()=>c.edit({loop:!c.snapshot.settings.loop})}>LOOP</button><button onClick={()=>void c.controller.refresh()}>REFRESH</button><span>{c.snapshot.frames.length?`${c.snapshot.index+1} / ${c.snapshot.frames.length}`:'LATEST ISSUANCE'}</span></div>;}
const objectKinds:WeatherObject['kind'][]=['cold','warm','stationary','occluded','trough','dryline','H','L','text','arrow','hurricane','tropical-storm'];
export function SynopticControls(){const c=useSynoptic();if(!c.active)return null;const s=c.snapshot.settings;return <div className="synoptic-controls"><div className="panel-heading">BROADCAST WEATHER</div>
 <BarLibrary value={s.barStyles} onChange={barStyles=>c.edit({barStyles})} targets={['title','lower','status']}/>
 <div className="synoptic-object-tools">{([['National',[-98,38],3.6],['Atlantic',[-55,28],3],['Gulf',[-85,23],4.5],['Pacific',[-120,22],3.5]] as const).map(([name,center,zoom])=><button key={name} disabled={!c.map} onClick={()=>c.map?.easeTo({center:[...center],zoom,duration:700})}>{name}</button>)}</div><label>Scene title<input value={s.textOverrides?.title??s.title} placeholder={PRODUCTS.find(p=>p.id===c.snapshot.productId)?.title} onChange={e=>c.edit({textOverrides:{...s.textOverrides,title:e.target.value}})}/></label>
 <label>Subtitle<input value={s.textOverrides?.subtitle??s.subtitle} onChange={e=>c.edit({textOverrides:{...s.textOverrides,subtitle:e.target.value}})}/></label>
 <label>Time text override<input value={s.textOverrides?.time??''} placeholder="Automatic valid time" onChange={e=>c.edit({textOverrides:{...s.textOverrides,time:e.target.value}})}/></label>
 <button onClick={()=>{const {time,...rest}=s.textOverrides??{};c.edit({textOverrides:rest});}}>Use automatic time</button>
 <button onClick={()=>c.edit({titleLayout:titleLayout()})}>Reset title size / position</button>
 <button onClick={()=>c.edit({textOverrides:{},title:'',subtitle:'',lower:''})}>Reset bar text</button>
 <small>Double-click bar text to edit. Drag any title corner to scale; drag the bar to move.</small>
 <label>Lower third<input value={s.textOverrides?.lower??s.lower} onChange={e=>c.edit({textOverrides:{...s.textOverrides,lower:e.target.value}})}/></label>
 {PRODUCTS.find(p=>p.id===c.snapshot.productId)?.family==='tropical'&&<label>Storm<select value={s.storm} onChange={e=>c.edit({storm:e.target.value})}><option value="">All active storms</option>{[...new Set(c.snapshot.payload?.data?.features.map(f=>String(f.properties?._storm??'')).filter(Boolean))].map(name=><option key={name}>{name}</option>)}</select></label>}<label>Operator forecast valid time<input type="datetime-local" value={s.forecastTime} onChange={e=>c.edit({forecastTime:e.target.value})}/></label>
 <label>Weather background<select value={s.background} onChange={e=>c.edit({background:e.target.value as SceneSettings['background']})}><option value="none">None</option><option value="radar">MRMS mosaic</option><option value="satellite">GOES infrared</option></select><button onClick={()=>void c.controller.refresh()}>Apply background</button></label>
 <label>Opacity<input type="range" min="0" max="1" step=".05" value={s.opacity} onChange={e=>c.edit({opacity:+e.target.value})}/></label>
 {(['titleVisible','legendVisible','labels','detailsVisible','contours'] as const).map(key=><label key={key}><input type="checkbox" checked={s[key]} onChange={e=>c.edit({[key]:e.target.checked})}/>{({titleVisible:'Title bar',legendVisible:'Legend',labels:'Labels',detailsVisible:'Feature details',contours:'Analysis contours'})[key]}</label>)}
 {c.snapshot.productId?.startsWith('glm')&&<label>Lightning window<select value={s.windowMinutes} onChange={e=>{c.edit({windowMinutes:+e.target.value});}}>{[1,5,10,15,30].map(n=><option key={n} value={n}>{n} minutes</option>)}</select><button onClick={()=>void c.controller.refresh()}>Apply window</button></label>}
 <div className="panel-heading">ON-AIR OBJECTS</div><div className="synoptic-object-tools">{objectKinds.map(kind=><button key={kind} aria-pressed={c.drawing===kind} onClick={()=>c.draw(c.drawing===kind?null:kind)}>{kind.toUpperCase()}</button>)}</div>
 {c.drawing&&<small>Click the map to place {c.drawing}. For fronts/arrows, add points and press Enter to finish; Escape cancels.</small>}
 <button disabled={!c.snapshot.payload?.objects?.length} onClick={()=>c.edit({manualSurface:true,objects:c.snapshot.payload!.objects!.map(o=>({...o,id:crypto.randomUUID(),origin:'operator'}))})}>Copy WPC objects for manual refinement</button>
 <label><input type="checkbox" checked={s.manualSurface} onChange={e=>c.edit({manualSurface:e.target.checked})}/>Replace WPC analysis with manual objects</label>
 {s.objects.map(o=><div key={o.id} className="synoptic-object-row"><button onClick={()=>c.select(o.id)}>{o.kind.toUpperCase()}</button><input aria-label="Object label" value={o.text} onChange={e=>c.edit({objects:s.objects.map(x=>x.id===o.id?{...x,text:e.target.value}:x)})}/><button onClick={()=>c.edit({objects:s.objects.filter(x=>x.id!==o.id)})}>×</button></div>)}
 <p role="status">{PRODUCTS.find(p=>p.id===c.snapshot.productId)?.source} · {c.snapshot.status}<br/>Data valid: {c.snapshot.payload?.time?new Date(c.snapshot.payload.time).toLocaleString():'Not supplied'}</p></div>;}
function Objects({snapshot,map,editable=false}:{snapshot:PackSnapshot;map:WeatherMap|null;editable?:boolean}){
 const context=useContext(Context),[revision,setRevision]=useState(0),[pending,setPending]=useState<[number,number][]>([]);void revision;
 useEffect(()=>{if(!map)return;const update=()=>setRevision(n=>n+1);map.on('move',update);map.on('resize',update);return()=>{map.off('move',update);map.off('resize',update);};},[map]);
 useEffect(()=>{if(!map||!editable||!context?.drawing)return;const kind=context.drawing;setPending([]);let points:[number,number][]=[];
  const save=()=>{if(!points.length)return;context.edit({objects:[...snapshot.settings.objects,{id:crypto.randomUUID(),kind,points,text:kind==='text'?'AIR MASS':'',origin:'operator'}]});context.draw(null);setPending([]);};
  const click=(e:any)=>{points=[...points,[e.lngLat.lng,e.lngLat.lat]];setPending(points);if(['H','L','text','hurricane','tropical-storm'].includes(kind))save();};
  const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){context.draw(null);setPending([]);}if(e.key==='Enter'&&points.length>1)save();};map.on('click',click);window.addEventListener('keydown',key);return()=>{map.off('click',click);window.removeEventListener('keydown',key);};
 },[map,editable,context?.drawing,snapshot.settings.objects]);
 if(!map)return null;
 const objects=[...(snapshot.settings.manualSurface?[]:snapshot.payload?.objects??[]),...snapshot.settings.objects];
 const width=map.getCanvas().clientWidth,height=map.getCanvas().clientHeight;
 const colors:Record<string,string>={cold:'#398eff',warm:'#ff4548',stationary:'#3299ff',occluded:'#d64dec',trough:'#ffad65',dryline:'#dd903e',H:'#368cff',L:'#ff3d43',text:'#ffffff',arrow:'#ffffff',hurricane:'#ff6267','tropical-storm':'#ffd355'};
 return <svg className="synoptic-objects" viewBox={`0 0 ${width} ${height}`}><defs><filter id="wx-shadow"><feDropShadow dx="1" dy="2" stdDeviation="2" floodOpacity=".8"/></filter><linearGradient id="wx-high" x2="0" y2="1"><stop stopColor="#d1eeff"/><stop offset=".4" stopColor="#4599ff"/><stop offset=".45" stopColor="#16478e"/><stop offset="1" stopColor="#79b5ff"/></linearGradient><linearGradient id="wx-low" x2="0" y2="1"><stop stopColor="#ffd7d7"/><stop offset=".4" stopColor="#ff6262"/><stop offset=".45" stopColor="#901727"/><stop offset="1" stopColor="#ff6565"/></linearGradient></defs>
 {objects.map(o=>{const pts=o.points.map(p=>map.project(p)),d=pts.map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' '),color=colors[o.kind],point=['H','L','text','hurricane','tropical-storm'].includes(o.kind);const symbols:ReactNode[]=[];let distance=18,sequence=0;
  for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],len=Math.hypot(b.x-a.x,b.y-a.y),angle=Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI;for(;distance<len;distance+=32){const x=a.x+(b.x-a.x)*distance/len,y=a.y+(b.y-a.y)*distance/len,alternate=sequence++%2,side=o.kind==='stationary'&&alternate?-1:1,c=o.kind==='stationary'&&alternate?'#ff4548':color;symbols.push(<g key={`${i}-${distance}`} transform={`translate(${x} ${y}) rotate(${angle}) scale(1 ${side})`}>{o.kind==='cold'||((o.kind==='stationary'||o.kind==='occluded')&&!alternate)?<path d="M-8,0 L0,-13 L8,0 Z" fill={c}/>:['warm','stationary','occluded','dryline'].includes(o.kind)?<path d="M-8,0 A8,8 0 0 1 8,0 Z" fill={o.kind==='dryline'?'none':c} stroke={c} strokeWidth="2"/>:null}</g>);}distance-=len;}
  return <g key={o.id} filter="url(#wx-shadow)" onClick={()=>editable&&context?.select(o.id)} style={{pointerEvents:editable?'auto':'none',cursor:editable?'pointer':undefined}}>{point?<g transform={`translate(${pts[0]?.x??0} ${pts[0]?.y??0})`}><text textAnchor="middle" fill={o.kind==='H'?'url(#wx-high)':o.kind==='L'?'url(#wx-low)':color} stroke="#eee" strokeWidth={o.kind==='text'?0:.7} fontSize={o.kind==='text'?30:o.origin==='WPC'&&map.getZoom()<5?36:54} fontWeight="900">{o.kind==='text'?o.text:o.kind==='hurricane'?'🌀':o.kind==='tropical-storm'?'TS':o.kind}</text>{snapshot.settings.labels&&o.kind!=='text'&&<text y="20" fill="white" textAnchor="middle" fontSize={o.origin==='WPC'&&map.getZoom()<5?13:16} fontWeight="700">{o.text}</text>}</g>:<><path d={d} fill="none" stroke={color} strokeWidth="4" strokeDasharray={o.kind==='trough'?'12 9':undefined} strokeLinecap="round"/>{symbols}{o.kind==='arrow'&&pts.length>1&&<path d="M-17,-10 L0,0 L-17,10" fill="none" stroke={color} strokeWidth="5" transform={`translate(${pts.at(-1)!.x} ${pts.at(-1)!.y}) rotate(${Math.atan2(pts.at(-1)!.y-pts.at(-2)!.y,pts.at(-1)!.x-pts.at(-2)!.x)*180/Math.PI})`}/>}</>}
  {editable&&context?.selected===o.id&&o.origin==='operator'&&pts.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="7" fill="white" stroke={color} strokeWidth="3" onPointerDown={e=>{e.stopPropagation();const target=e.currentTarget;target.setPointerCapture(e.pointerId);const move=(event:PointerEvent)=>{const rect=map.getCanvas().getBoundingClientRect(),ll=map.unproject([event.clientX-rect.left,event.clientY-rect.top]);context.edit({objects:snapshot.settings.objects.map(x=>x.id===o.id?{...x,points:x.points.map((q,j)=>j===i?[ll.lng,ll.lat]:q)}:x)});};const up=()=>{target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',up);};target.addEventListener('pointermove',move);target.addEventListener('pointerup',up,{once:true});}}/>)}</g>;
 })}{pending.length>0&&<polyline points={pending.map(p=>{const q=map.project(p);return `${q.x},${q.y}`;}).join(' ')} stroke="white" strokeWidth="3" fill="none"/>}</svg>;
}
export function SynopticShell({snapshot,map,editable=false}:{snapshot:PackSnapshot;map:WeatherMap|null;editable?:boolean}){
 const context=useContext(Context);const edit=editable?context?.edit:undefined;
 const [details,setDetails]=useState<Record<string,unknown>|null>(null),[,tick]=useState(0);const product=PRODUCTS.find(p=>p.id===snapshot.productId),s=snapshot.settings;
 useEffect(()=>{const timer=setInterval(()=>tick(n=>n+1),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!map||!s.detailsVisible)return;const click=(e:any)=>{const layers=['rbrwx-synoptic-fill','rbrwx-synoptic-line','rbrwx-synoptic-point'].filter(l=>map.getLayer(l));if(layers.length)setDetails(map.queryRenderedFeatures(e.point,{layers})[0]?.properties??null);};map.on('click',click);return()=>{map.off('click',click);};},[map,s.detailsVisible]);
 useEffect(()=>setDetails(null),[snapshot.productId]);
 if(!product)return null;const expired=!!snapshot.payload?.expires&&snapshot.payload.expires<Date.now(),payload=expired?null:snapshot.payload,valid=payload?.time?new Date(payload.time).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}):product.kind==='manual'&&s.forecastTime?`${new Date(s.forecastTime).toLocaleString()} · OPERATOR FORECAST`:'VALID TIME NOT SUPPLIED';
 const field=(id:string,value:string,label:string)=> <EditableText label={label} value={s.textOverrides?.[id]??value} edit={edit?value=>edit({textOverrides:{...s.textOverrides,[id]:value}}):undefined}/>;
 const storm=payload?.data?.features.filter(f=>f.geometry.type==='Point'&&f.properties?.MAXWIND!==undefined&&(!s.storm||f.properties._storm===s.storm)).sort((a,b)=>Number(a.properties?.TAU??0)-Number(b.properties?.TAU??0))[0]?.properties;
 return <div className={`synoptic-shell synoptic-shell--${product.family}`}>
 {s.titleVisible&&<TitleBar appearance={barPresentation(s.barStyles?.title)} settings={s} title={s.title||product.title} time={`${payload?.timeLabel??'VALID'} · ${valid}`} legend={payload?.legend} edit={edit}/>}
 <Objects snapshot={{...snapshot,payload}} map={map} editable={editable}/>
 {(!payload||expired)&&<div className="synoptic-unavailable" {...barAttributes(s.barStyles?.status)}><EditableText label="Status bar text" value={s.textOverrides?.status??(expired?'UNAVAILABLE · PRODUCT EXPIRED':snapshot.status)} edit={edit?value=>edit({textOverrides:{...s.textOverrides,status:value}}):undefined}/></div>}
 {product.family==='tropical'&&storm&&<aside className="synoptic-storm"><strong>{field('storm:name',String(storm.STORMNAME??'TROPICAL SYSTEM'),'Storm name')}</strong><dl>{[['Wind',`${storm.MAXWIND??'—'} kt`],['Gusts',`${storm.GUST??'—'} kt`],['Pressure',`${storm.MSLP??'—'} hPa`],['Motion',`${storm.TCDIR??'—'}° at ${storm.TCSPD??'—'} kt`],['Location',`${storm.LAT??'—'}°, ${storm.LON??'—'}°`]].map(([k,v])=><div key={k}><dt>{field(`storm:label:${k}`,k,`${k} label`)}</dt><dd>{field(`storm:value:${k}`,v,`${k} value`)}</dd></div>)}</dl><small>{field('storm:advisory',`Advisory ${storm.ADVISNUM??'—'} · ${storm.ADVDATE??''}`,'Storm advisory text')}</small></aside>}
 {(s.textOverrides?.lower??s.lower)&&<div className="synoptic-lower" {...barAttributes(s.barStyles?.lower)}><EditableText label="Lower third text" value={s.textOverrides?.lower??s.lower} edit={edit?value=>edit({textOverrides:{...s.textOverrides,lower:value}}):undefined}/></div>}
 {s.detailsVisible&&details&&<aside className="synoptic-details"><button onClick={()=>setDetails(null)}>×</button>{Object.entries(details).filter(([k])=>!k.startsWith('_')).map(([k,v])=><div key={k}><b>{field(`detail:label:${k}`,k.replaceAll('_',' '),`${k} label`)}</b><span>{field(`detail:value:${k}`,String(v??'—'),`${k} text`)}</span></div>)}</aside>}
 </div>;
}
export function SynopticOverlay(){const c=useSynoptic();return c.active?<SynopticShell snapshot={c.snapshot} map={c.map} editable/>:null;}
