import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createServer} from 'vite';import {chromium} from 'playwright';
const out=path.resolve(process.env.RBRWX_RENDER_OUT??'render-results');fs.mkdirSync(out,{recursive:true});const server=await createServer({server:{hmr:false,watch:null,host:'127.0.0.1',port:1427,strictPort:true}});await server.listen();let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.RBRWX_CHROMIUM||undefined,args:['--no-sandbox','--enable-unsafe-swiftshader'],proxy:process.env.HTTPS_PROXY?{server:process.env.HTTPS_PROXY,bypass:'127.0.0.1,localhost'}:undefined});const page=await browser.newPage({ignoreHTTPSErrors:!!process.env.RBRWX_CHROMIUM,viewport:{width:1280,height:720}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:1427/scripts/render/editor.html');await page.waitForFunction(()=>!!window.editors);await page.evaluate(()=>window.editors.graphics.toggle('title'));
 const title=page.getByLabel('title text',{exact:true});await title.dblclick();await title.fill('Local Weather');await title.press('Enter');await page.waitForFunction(()=>window.editors.graphics.copy.title==='Local Weather');
 await page.evaluate(()=>window.editors.graphics.history('save'));await title.dblclick();await title.fill('Changed');await title.press('Escape');assert.equal(await title.innerText(),'Local Weather');
 await title.dblclick();await title.fill('Changed');await title.press('Enter');await page.evaluate(()=>window.editors.graphics.history('undo'));assert.equal(await title.innerText(),'Local Weather');await page.evaluate(()=>window.editors.graphics.history('redo'));assert.equal(await title.innerText(),'Changed');await page.evaluate(()=>window.editors.graphics.history('restore'));assert.equal(await title.innerText(),'Local Weather');
 await title.click({button:'right'});assert.ok(await page.getByRole('button',{name:'Save point',exact:true}).isVisible());await page.screenshot({path:path.join(out,'inline-title-controls.png')});await page.getByRole('button',{name:'Done',exact:true}).click();
 await page.evaluate(()=>window.setEditorScene('b'));await page.waitForFunction(()=>window.editors.graphics.scene.id==='b');await page.evaluate(()=>window.editors.graphics.toggle('title'));assert.equal(await title.innerText(),'Automatic b');await page.evaluate(()=>window.setEditorScene('a'));await page.waitForFunction(()=>window.editors.graphics.scene.id==='a');assert.equal(await title.innerText(),'Local Weather');
 await page.waitForTimeout(350);await page.reload();await page.waitForFunction(()=>!!window.editors);assert.equal(await title.innerText(),'Local Weather');
 await page.evaluate(()=>window.setEditorScene('forecast-a','forecast'));await page.waitForFunction(()=>window.editors.forecast.objects.length>0);const text=page.locator('.forecast-object__text').first();await text.dblclick();await text.fill('Forecast edit');await text.press('Enter');await page.waitForFunction(()=>window.editors.forecast.objects.some(o=>o.text==='Forecast edit'||o.textOverride==='Forecast edit'));await page.evaluate(()=>window.editors.forecast.history('undo'));assert.notEqual(await text.innerText(),'Forecast edit');
 await text.click({button:'right'});assert.ok(await page.getByRole('button',{name:'Restore',exact:true}).isVisible());await page.screenshot({path:path.join(out,'forecast-inline-controls.png')});const templates=['right-now','today','tonight','today-tonight','hourly','seven-day','planner','weekend','need-to-know','blank'];const sceneResults=[];
 for(const template of templates){await page.evaluate(template=>window.setEditorScene('audit-'+template,'graphic.'+template),template);await page.waitForFunction(template=>window.editors.forecast.template===template,template);if(!['need-to-know','blank'].includes(template)){await page.waitForFunction(()=>window.editors.forecast.status==='ready'||window.editors.forecast.status==='unavailable',null,{timeout:120000});assert.equal(await page.evaluate(()=>window.editors.forecast.status),'ready');}await page.waitForTimeout(300);const overflow=await page.locator('.forecast-object__text').evaluateAll(nodes=>nodes.filter(n=>n.scrollWidth>n.clientWidth+2||n.scrollHeight>n.clientHeight+2).map(n=>n.textContent));sceneResults.push({template,overflow});await page.screenshot({path:path.join(out,'scene-'+template+'.png')});assert.deepEqual(overflow,[],template+' text overflow');}
 fs.writeFileSync(path.join(out,'forecast-scenes.json'),JSON.stringify(sceneResults,null,2));assert.deepEqual(errors,[]);console.log('PASS browser: shared editor save/cancel, undo/redo/restore, inline menus, scene isolation, reload persistence, forecast text editing');
}finally{await browser?.close();await server.close();}
