import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createServer} from 'vite';import {chromium} from 'playwright';
const out=path.resolve(process.env.RBRWX_RENDER_OUT??'render-results');fs.mkdirSync(out,{recursive:true});const server=await createServer({server:{hmr:false,watch:null,host:'127.0.0.1',port:1428,strictPort:true}});await server.listen();let browser;
try{browser=await chromium.launch({headless:true,executablePath:process.env.RBRWX_CHROMIUM||undefined,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],proxy:process.env.HTTPS_PROXY?{server:process.env.HTTPS_PROXY,bypass:'localhost,127.0.0.1'}:undefined});const page=await browser.newPage({viewport:{width:960,height:600},ignoreHTTPSErrors:!!process.env.RBRWX_CHROMIUM});await page.goto('http://127.0.0.1:1428/scripts/render/harness.html');await page.waitForFunction(()=>!!window.audit);
const expired=await page.evaluate(()=>window.audit.faults());assert.equal(expired.expiredLayers,0);
let observationAge=4*3600000;
await page.route('https://api.weather.gov/**',route=>{const url=route.request().url();const body=url.includes('/points/')?{properties:{observationStations:'https://api.weather.gov/gridpoints/TEST/1,1/stations'}}:url.endsWith('/stations')?{features:[{properties:{stationIdentifier:'KTEST',name:'Test station'},geometry:{coordinates:[-98,35]}},{properties:{stationIdentifier:'KTEST2',name:'Test station 2'},geometry:{coordinates:[-99,35]}}]}:{properties:{timestamp:new Date(Date.now()-observationAge).toISOString(),temperature:{value:25,unitCode:'wmoUnit:degC'}}};return route.fulfill({status:200,contentType:'application/geo+json',body:JSON.stringify(body)});});
const expiredObservations=await page.evaluate(()=>window.audit.imagery('observations'));assert.equal(expiredObservations.status,'unavailable');assert.equal(expiredObservations.paintedReports,0);assert.equal(expiredObservations.pixels,0);await page.screenshot({path:path.join(out,'expired-observations.png')});
observationAge=2*3600000;const staleObservations=await page.evaluate(()=>window.audit.imagery('observations'));assert.equal(staleObservations.status,'stale');assert.ok(staleObservations.pixels>0);
observationAge=60000;const freshObservations=await page.evaluate(()=>window.audit.imagery('observations'));assert.equal(freshObservations.status,'fresh');assert.ok(freshObservations.pixels>0);await page.screenshot({path:path.join(out,'fresh-observations.png')});await page.unrouteAll();
await page.route('https://api.weather.gov/alerts/**',route=>route.fulfill({status:503,body:'Provider failure'}));const outage=await page.evaluate(()=>window.audit.product('alerts'));assert.equal(outage.loaded,false);assert.match(outage.status,/503/);assert.equal(outage.layers,1);await page.screenshot({path:path.join(out,'provider-failure.png')});await page.unrouteAll();
await page.route('https://noaa-rtma-pds.s3.amazonaws.com/**',async route=>{if(route.request().headers()['range'])await route.fulfill({status:206,contentType:'application/octet-stream',body:Buffer.alloc(32)});else await route.continue();});const corrupt=await page.evaluate(()=>window.audit.product('rtma-temperature'));assert.equal(corrupt.loaded,false);assert.match(corrupt.status,/Truncated|GRIB|range/i);assert.equal(corrupt.layers,1);await page.screenshot({path:path.join(out,'corrupt-grid.png')});
fs.writeFileSync(path.join(out,'failure-results.json'),JSON.stringify({expired,expiredObservations,staleObservations,freshObservations,outage,corrupt},null,2));console.log('PASS WebGL observation age and failures: expired layers removed, HTTP 503 shown without old output, corrupt GRIB rejected before display');
}finally{await browser?.close();await server.close();}
