import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const ts = require('../broadcast/vendor/typescript/typescript.cjs');
const source = await readFile(new URL('../../src/broadcast-graphics/state.ts', import.meta.url), 'utf8');
const js = ts.transpileModule(source, {compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const { freshCopy, freshLayouts, titleText, changeLayout, constrain } = await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const copy = freshCopy();
assert.equal(titleText({id:'a',title:'Radar'},copy),'Radar');
assert.equal(titleText({id:'b',title:'Satellite'},copy),'Satellite');
assert.equal(titleText({id:'b',title:'Satellite'},{...copy,manual:true,title:''}),'');
assert.equal(titleText({id:'b',title:'Satellite'},{...copy,manual:true,title:'Custom'}),'Custom');
const start = freshLayouts().title;
assert.equal(changeLayout('title',{...start,scale:.5},100,50,false).x,124);
assert.equal(changeLayout('title',{...start,scale:.5},100,50,false).y,77);
assert.ok(changeLayout('title',{...start,scale:.5},100,0,true).scale > .5);
assert.equal(constrain('title',{x:-100,y:-100,scale:-1}).scale,.25);
assert.equal(constrain('title',{x:-100,y:-100,scale:-1}).x,0);
const ui = await readFile(new URL('../../src/broadcast-graphics/Graphics.tsx',import.meta.url),'utf8');
assert.match(ui,/title: false, lower: false, ticker: false/);
assert.match(ui,/onDoubleClick/); assert.match(ui,/setPointerCapture/);
assert.doesNotMatch(ui,/from ['"].*(?:broadcast-host|\/broadcast['"]|\/map)/);
const css = await readFile(new URL('../../src/broadcast-graphics/graphics.css',import.meta.url),'utf8');
assert.doesNotMatch(css,/cursor:\s*(?:move|grab|nwse-resize)|is-selected|resize-handle|remove-icon/);
console.log('Integrated graphics scene, blank text, drag, scale, startup, and isolation checks: PASS');
