import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),ts=require('../broadcast/vendor/typescript/typescript.cjs');
const read=file=>fs.readFileSync(new URL('../../'+file,import.meta.url),'utf8');
function commands({forecastActive=false,synopticActive=true,radarEnabled=false}={}){
 const calls=[];const record=name=>(...args)=>calls.push([name,...args]);
 const controller={step:record('radar.step'),play:record('radar.play'),refresh:record('radar.refresh'),setPrimaryRadar:record('radar.site')};
 const presets={};
 const radar={enabled:radarEnabled,controller,snapshot:{primaryRadarId:'KEWX'},options:{sweepsEnabled:false},toggle:record('radar.toggle'),setEnabled:record('radar.enabled'),edit:record('radar.edit')};
 const qpf={active:true,enabled:true,opacity:.8,editOpacity:record('qpf.opacity'),setEnabled:record('qpf.enabled')};
 const forecast={active:forecastActive,history:record('forecast.history'),showTitle:record('forecast.title')};
 const synoptic={active:synopticActive,history:record('synoptic.history'),step:record('synoptic.step'),play:record('synoptic.play'),map:{getCenter:()=>({lng:-98,lat:29}),getZoom:()=>6,getBearing:()=>0,getPitch:()=>0,jumpTo:record('map.jump')},setProduct:record('synoptic.product'),edit:record('synoptic.edit'),snapshot:{productId:'rtma-temperature',settings:{textOverrides:{title:'old',time:'old',subtitle:'retain'}}}};
 const weather={product:'observations',options:{opacity:.7},setProduct:record('weather.product'),edit:record('weather.edit')};
 const tools={setEnabled:record('tools.enabled'),enabled:{warnings:true,surge:false},mode:'none',snapshot:{objects:{strokes:[1,2]}},toggle:record('overlay.toggle'),edit:record('tools.edit'),refresh:record('tools.refresh'),setMode:record('tools.mode'),setColor:record('tools.color')};
 const graphics={history:record('graphics.history'),visible:{title:false},edit:record('graphics.edit'),toggle:record('graphics.toggle')};
 const ewx={state:{enabled:false},edit:record('ewx.edit'),refresh:record('ewx.refresh')};
 const mocks={'../broadcast':{useBroadcast:()=>({})},'../broadcast-graphics/sceneDocuments':{useSceneRecords:()=>[presets,update=>Object.assign(presets,update(presets))]},'./operatorCommands':{isOperatorCommand:value=>JSON.parse(read('src/broadcast-host/operatorCommands.json')).includes(value)||/^(speed:|color:|seek:|radar-site:)/.test(value)},'./RadarOverlay':{useRadarOverlay:()=>radar},'./ForecastGraphicsHost':{useForecastGraphics:()=>forecast},'./QpfHost':{useQpf:()=>qpf},'../current-weather/CurrentWeather':{useCurrentWeather:()=>weather},'../synoptic/Scene':{useSynoptic:()=>synoptic},'../synoptic/OnAirTools':{useOnAirTools:()=>tools,OVERLAYS:[{id:'warnings'},{id:'surge'}]},'../broadcast-graphics/Graphics':{useGraphics:()=>graphics},'../current-weather/EwxAlerts':{useEwxAlerts:()=>ewx},'../synoptic/model':{PRODUCTS:[{id:'mrms-qpe1',family:'mrms'}]}};
 const exports={};new Function('exports','require',ts.transpileModule(read('src/broadcast-host/OnAirMenu.tsx'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText)(exports,id=>mocks[id]??(id.startsWith('.')?{}:require(id)));
 return {dispatch:exports.useOnAirCommands(),calls,presets};
}
test('radar choices preserve QPF, synoptic, observations, satellite and graphic scene state',()=>{for(const forecastActive of [true,false]){const {dispatch,calls}=commands({forecastActive});for(const field of ['reflectivity','velocity','hydro']){calls.length=0;dispatch('radar:'+field);assert.deepEqual(calls,[['radar.enabled',true],['radar.edit',{radarField:field,mrmsEnabled:false}]]);}calls.length=0;dispatch('radar-toggle');dispatch('radar-off');assert.deepEqual(calls,[['radar.toggle'],['radar.enabled',false]]);}});
test('title refresh targets each visible scene renderer',()=>{let c=commands({forecastActive:true});c.dispatch('bar-refresh');assert.deepEqual(c.calls,[['forecast.title',true]]);c=commands();c.dispatch('bar-refresh');assert.deepEqual(c.calls,[['synoptic.edit',{titleVisible:true,title:'',textOverrides:{subtitle:'retain'}}]]);c=commands({synopticActive:false});c.dispatch('bar-refresh');assert.deepEqual(c.calls,[['graphics.edit',{manual:false}],['graphics.toggle','title']]);});
test('weather off clears QPF, radar and enabled hazard overlays',()=>{const {dispatch,calls}=commands();dispatch('layers-off');assert.deepEqual(calls,[['radar.enabled',false],['qpf.enabled',false],['overlay.toggle','warnings'],['weather.product','map'],['synoptic.product',null]]);});
test('sweep, alert, drawing, tracking and product menu commands have handlers',()=>{const {dispatch,calls}=commands();for(const command of ['sweeps','ewx-toggle','ewx-refresh','pen','track','pen-undo','pen-clear','track-clear','speed:40','color:#123abc','overlay:surge','satellite:visible','mrms:mrms-qpe1','overlays-refresh'])assert.equal(dispatch(command),true,command);assert.ok(calls.some(c=>c[0]==='radar.edit'));assert.ok(calls.some(c=>c[0]==='tools.refresh'));assert.equal(dispatch('not-a-command'),false);});
test('native popout bridge accepts independent radar commands and mirror strips editing controls',()=>{const native=read('src-tauri/src/lib.rs')+read('src/broadcast-host/operatorCommands.json'),mirror=read('src/broadcast-host/ProgramMirror.tsx');for(const command of ['radar-toggle','radar-off'])assert.ok(native.includes('"'+command+'"'));assert.ok(mirror.includes('.wx-inline-controls'));assert.ok(mirror.includes('.forecast-inline-controls'));});

test('all transports route to radar while it overlays an active synoptic scene',()=>{const c=commands({radarEnabled:true});for(const action of ['previous','next','play-pause','refresh'])c.dispatch(action);assert.deepEqual(c.calls,[['radar.step',-1],['radar.step',1],['radar.play'],['radar.refresh']]);});
test('saved preset restores viewport and explicit layer/options without changing selected scene',()=>{const old=global.requestAnimationFrame;global.requestAnimationFrame=fn=>fn();try{const c=commands({radarEnabled:true});c.dispatch('preset:save:1');assert.equal(c.presets['1'].radar,true);assert.deepEqual(c.presets['1'].center,[-98,29]);c.dispatch('preset:load:1');assert.ok(c.calls.some(v=>v[0]==='radar.site'&&v[1]==='KEWX'));assert.ok(c.calls.some(v=>v[0]==='tools.enabled'&&v[1].warnings));assert.ok(c.calls.some(v=>v[0]==='map.jump'&&v[1].zoom===6));}finally{global.requestAnimationFrame=old;}});
test('edit history routes to the active renderer',()=>{for(const forecastActive of [true,false]){const c=commands({forecastActive});c.dispatch('edit:restore');assert.equal(c.calls[0][0],forecastActive?'forecast.history':'synoptic.history');}});
