import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),ts=require('../broadcast/vendor/typescript/typescript.cjs');
function load(file){const exports={};const code=ts.transpileModule(fs.readFileSync(new URL('../../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;new Function('exports','require',code)(exports,require);return exports;}
const {resizeBox}=load('src/broadcast-graphics/ResizeBox.tsx'),{ewxAlerts}=load('src/current-weather/ewx-alert-data.ts'),{cityTimings,destination}=load('src/synoptic/tracking.ts'),{radarProductLayer,imageRequest}=load('src/current-weather/public-imagery.ts');
test('side resizing changes width without scaling text; opposite edge remains fixed',()=>{const box={x:10,y:10,width:70,fontScale:1.3},canvas={width:1000,height:600},rect={width:700,height:100};const e=resizeBox(box,-100,0,'e',canvas,rect);assert.equal(e.width,60);assert.equal(e.fontScale,1.3);assert.equal(e.x,10);const w=resizeBox(box,100,0,'w',canvas,rect);assert.equal(w.x+w.width,80);assert.equal(w.fontScale,1.3);});
for(const edge of ['nw','ne','sw','se'])test(`${edge} corner scales bar and text; text-only resizing leaves bounds intact`,()=>{const box={x:10,y:10,width:70,height:20,fontScale:1},canvas={width:1000,height:600},rect={width:700,height:120};const dx=edge.includes('w')?70:-70,dy=edge.includes('n')?12:-12;const next=resizeBox(box,dx,dy,edge,canvas,rect);assert.ok(next.width<70);assert.equal(next.height/next.width,20/70);const text=resizeBox(box,dx,dy,edge,canvas,rect,true);assert.equal(text.width,70);assert.equal(text.height,20);assert.equal(text.x,10);assert.ok(text.fontScale<1);});
test('EWX crawl excludes other offices, expired/test/cancelled alerts, deduplicates and prioritizes',()=>{const now=Date.now(),feature=(id,patch={})=>({id,properties:{status:'Actual',messageType:'Alert',senderName:'NWS Austin/San Antonio TX',sent:new Date(now-1000).toISOString(),expires:new Date(now+60000).toISOString(),severity:'Moderate',event:'Flood Advisory',...patch}});const data={features:[feature('one'),feature('one'),feature('old',{expires:new Date(now-1).toISOString()}),feature('test',{status:'Test'}),feature('cancel',{messageType:'Cancel'}),feature('other',{senderName:'NWS Houston/Galveston TX'}),feature('urgent',{severity:'Extreme'})]};assert.deepEqual(ewxAlerts(data,now).map(a=>a.id),['urgent','one']);assert.throws(()=>ewxAlerts({}),/Invalid/);});
test('capability-qualified velocity/classification never fall back to reflectivity',()=>{const xml='<Name>kewx_sr_bref</Name><Name>kewx_sr_bvel</Name><Name>kewx_bdhc</Name>';assert.equal(radarProductLayer(xml,'KEWX','velocity'),'kewx_sr_bvel');assert.equal(radarProductLayer(xml,'KEWX','hydro'),'kewx_bdhc');assert.throws(()=>radarProductLayer('<Name>kewx_sr_bref</Name>','KEWX','velocity'),/does not advertise/);assert.throws(()=>radarProductLayer(xml,'KHGX','hydro'),/does not advertise/);assert.equal(new URL(imageRequest('satellite',Date.now(),[0,0,1,1],100,100,'water_vapor')).searchParams.get('LAYERS'),'goes_water_vapor_imagery');});
test('operator city timing uses direction and speed and excludes cities behind/off-track',()=>{const origin=[-98,30],ahead=destination(origin,90,20),cities=[{name:'Ahead',point:destination(origin,90,48.28032)},{name:'Behind',point:destination(origin,270,10)},{name:'Off track',point:destination(origin,0,40)}];const times=cityTimings(origin,ahead,30,cities);assert.equal(times.length,1);assert.ok(Math.abs(times[0].minutes-60)<.01);assert.deepEqual(cityTimings(origin,ahead,0,cities),[]);});
