import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),ts=require('../broadcast/vendor/typescript/typescript.cjs');
function load(file,mocks={}){const exports={};const code=ts.transpileModule(fs.readFileSync(new URL('../../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('exports','require',code)(exports,id=>mocks[id]??require(id));return exports;}
const {changeEntry,historyEntry}=load('src/broadcast-graphics/sceneDocuments.ts');
const fresh=()=>({value:{title:'Automatic',width:80},past:[],future:[],stamp:0});
test('undo/redo, named restore point and reset retain independent saved content',()=>{let e=fresh();e=changeEntry(e,{title:'Custom',width:60},1000);e=historyEntry(e,'save',fresh().value);e=changeEntry(e,{title:'New',width:50},2000);e=historyEntry(e,'undo',fresh().value);assert.equal(e.value.title,'Custom');e=historyEntry(e,'redo',fresh().value);assert.equal(e.value.title,'New');e=historyEntry(e,'restore',fresh().value);assert.equal(e.value.title,'Custom');e=historyEntry(e,'reset',fresh().value);assert.equal(e.value.title,'Automatic');e=historyEntry(e,'undo',fresh().value);assert.equal(e.value.title,'Custom');});
test('grouped size edits are one undo and new edits invalidate redo',()=>{let e=changeEntry(fresh(),{title:'Automatic',width:70},1000,true);e=changeEntry(e,{title:'Automatic',width:65},1100,true);assert.equal(e.past.length,1);e=historyEntry(e,'undo',fresh().value);assert.equal(e.value.width,80);e=changeEntry(e,{title:'New',width:80},2000);assert.equal(e.future.length,0);for(let i=0;i<100;i++)e=changeEntry(e,{title:String(i),width:80},3000+i*500);assert.equal(e.past.length,50);});
const {hrrrFrames,checkModelTime}=load('src/synoptic/futurecast.ts',{'./providers':{}});
const now=Date.UTC(2026,9,7,12),keys=hour=>Array.from({length:19},(_,f)=>`hrrr.20261007/conus/hrrr.t${hour}z.wrfsfcf${String(f).padStart(2,'0')}.grib2`);
test('HRRR chooses a complete single run and rejects stale or incomplete cycles',()=>{const frames=hrrrFrames([...keys('10'),...keys('11').slice(0,8)],now);assert.equal(frames.length,19);assert.ok(frames.every(f=>f.runTime===now-7200000));assert.equal(frames[18].time,now+16*3600000);assert.throws(()=>hrrrFrames(keys('11').slice(0,18),now),/complete/);assert.throws(()=>hrrrFrames(keys('01'),now),/fresh/);assert.throws(()=>checkModelTime({family:'futurecast'},frames[1],frames[1].runTime,frames[1].time+3600000,now),/differs/);});
const commands=JSON.parse(fs.readFileSync(new URL('../../src/broadcast-host/operatorCommands.json',import.meta.url)));
const {isOperatorCommand}=load('src/broadcast-host/operatorCommands.ts',{'./operatorCommands.json':{default:commands}});
test('one shared command registry covers static commands and bounds dynamic requests',()=>{for(const c of commands)assert.ok(isOperatorCommand(c));for(const c of ['seek:-1','seek:1000','preset:load:9','radar-site:<script>','speed:Infinity','color:red'])assert.equal(isOperatorCommand(c),false,c);assert.ok(isOperatorCommand('seek:18'));assert.ok(isOperatorCommand('radar-site:KEWX'));const native=fs.readFileSync(new URL('../../src-tauri/src/lib.rs',import.meta.url),'utf8');assert.ok(native.includes('include_str!("../../src/broadcast-host/operatorCommands.json")'));});
const {FORECAST_LOCATIONS,validLocation}=load('src/forecast-graphics/locations.ts');
const {loadForecastGraphicsData}=load('src/forecast-graphics/forecastData.ts',{'./locations':{FORECAST_LOCATIONS,validLocation}});
test('selected location uses NWS coordinates/timezone and rejects stale issuance',async()=>{const original=global.fetch,calls=[];let stale=false;global.fetch=async url=>{calls.push(url);return {ok:true,json:async()=>url.includes('/points/')?{properties:{timeZone:'America/Denver',forecast:'forecast',forecastHourly:'hourly',relativeLocation:{properties:{city:'Denver',state:'CO'}}}}:{properties:{updateTime:new Date(Date.now()-(stale?90000000:1000)).toISOString(),periods:[{name:'Today',startTime:new Date().toISOString(),endTime:new Date(Date.now()+3600000).toISOString(),temperature:70,temperatureUnit:'F',isDaytime:true}]}}};};try{const d=await loadForecastGraphicsData(undefined,{name:'Denver',lat:39.7392,lon:-104.9903});assert.ok(calls[0].includes('39.7392,-104.9903'));assert.equal(d.timeZone,'America/Denver');stale=true;await assert.rejects(()=>loadForecastGraphicsData(),/stale/);}finally{global.fetch=original;}});
const {DecodeWorker}=load('src/synoptic/DecodeWorker.ts');
test('decode worker is reused for completed frames and replaced after cancellation',async()=>{let created=0,last;class Fake{terminated=false;postMessage(data){queueMicrotask(()=>this.onmessage?.({data}));}terminate(){this.terminated=true;}}const runner=new DecodeWorker(()=>{created++;return last=new Fake();});assert.deepEqual(await runner.run({frame:1},new AbortController().signal),{frame:1});await runner.run({frame:2},new AbortController().signal);assert.equal(created,1);const abort=new AbortController(),pending=runner.run({},abort.signal);abort.abort();await assert.rejects(()=>pending,/Cancelled/);assert.equal(last.terminated,true);await runner.run({},new AbortController().signal);assert.equal(created,2);runner.destroy();assert.equal(last.terminated,true);});

const {usableObservation}=load('src/current-weather/observations.ts');
test('observations exclude expired, invalid and future reports while allowing recently stale reports',()=>{const now=Date.now();assert.ok(usableObservation({time:now-2*3600000},now));for(const time of [NaN,now-4*3600000,now+6*60000])assert.equal(usableObservation({time},now),false);});
